config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  # TODO: Agregar seguridad a esto
  # mount Split::Dashboard, at: 'split'
  # Business
  get "/business", to: "home#business", as: :home_business
  get "/pricing", to: "home#pricing", as: :price_business

  # search
  get "/search", to: "searchs#show", as: "search"
  # users
  devise_for :users, :controllers => {sessions: "users/sessions"}
  devise_scope :user do
    get 'acceder', to: 'users/sessions#new' #, as: :new_user_session
    post "/guest", to: "users/sessions#continue_as_guest", as: "continue_as_guest"
  end
  get "/my-profile", to: "users#my_profile", as: "my_profile"
  get "/my-profile/edit", to: "users#edit", as: "edit_my_profile"
  resources :users, only: [:show, :update] do
    collection do
      patch 'update_password'
    end
  end
  #Address
  resources :addresses

  #cart
  # delete "/delete_product/:product_id", to: "carts#delete_product", as: "delete_product_to_cart"
  # put "/update_item/:item_id", to: "carts#update_item", as: "update_item_to_cart"
  # post "/add_to_cart/:place_id/:product_id", to: "carts#add_product", as: "add_product_to_cart"

  # checkouts
  get 'checkout', to: "checkouts#show"
  resources :checkouts, only: [:show, :create]
  get "/cart", to: "carts#show", as: "my_public_cart"

  #Public places
  resources :places, only: [:show, :index], path: "place" do
    # get "/catalog", to: "places#catalog", as: :catalog
    put '/:cart_id/delivery-options', to: "delivery_options#update", as: "delivery_options"
    resources :products do
      post "/cart/add_item", to: "carts#add_product", as: "add_to_cart"
    end

    resources :items, path: "departments", only: [:index, :show]
    patch "/cart/:cart_item_id/update_item", to: "carts#update_item", as: "update_cart_item"
    get "/cart", to: "carts#show", as: "my_cart"
    get "/cart/edit", to: "carts#show", as: "edit_my_cart"
    post "/cart", to: "carts#create_charge", as: "create_charge"
    get "/:cart_id/success", to: "carts#success", as: "success_checkout"
    put "/cart/payment-method", to: "carts#payment_method", as: "update_payment_method"
  end

  # Dashboard
  get "/dashboard", to: "dashboard/places#my_place", as: "my_place" # Index dashboard
  # Webhooks
  post "/hooks", to: "dashboard/hooks#hooks"
  post "/hooks_connect", to: "dashboard/hooks#connect"
  # mount StripeEvent::Engine, at: '/hooks'
  namespace :dashboard do
    # Uploads
    post "/upload/:model/:slug/:attribute", to: "image#upload", as: "upload_image"
    get "/upgrade", to: "places#upgrade", as: :upgrade_plan
    get "/upgrade/:subscription_id", to: "subscriptions#new", as: :new_subscription
    post "/upgrade/:subscription_id", to: "subscriptions#create", as: :create_subscription
    # Payment Links
    resources :payment_links, only: [:index]
    resources :promotions, only: [:index]
    resources :loyalties, only: [:index]
    # Items
    resources :items, path: "departments" do
      delete "/:product_id", to: "items#remove_product", as: :remove_product
      get "/add-products", to: "items#add_products", as: :add_products
      post "/add-product/:product_id", to: "items#add_product", as: :add_product
    end
    resources :subscriptions, only: [:new]
    resources :customers, only: [:index, :show]
    # Products
    resources :products do
      post "/update_status", to: "products#update_status", as: :update_status
      get "/edit/inventory", to: "products#edit_inventory", as: :edit_inventory
      get "/edit/variants", to: "products#edit_variants", as: :edit_variants
      get "/edit/variants/new", to: "aggregate_categories#new", as: :new_variant
      get "/edit/variants/:id", to: "aggregate_categories#show", as: :edit_variant
      # patch "/edit/variants/:id", to: "aggregate_categories#update", as: :update_variant
      resources :aggregate_categories, :path => 'variants' do
        resources :aggregates
      end
    end
    # Places
    resources :orders do
      patch "/process", to: "orders#process_order", as: :process_item
      patch "/receive", to: "orders#receive_order", as: :receive_item
      patch "/send", to: "orders#send_order", as: :send_item
      patch "/cancel", to: "orders#cancel_order", as: :cancel_item
    end
    delete "/delete-place", to: "places#destroy", as: "destroy_my_place"
    get "/settings", to: "places#edit", as: "edit_my_place"
    get "/settings/general", to: "settings#general", as: "edit_general_my_place"
    get "/settings/shipping", to: "settings#shipping", as: "edit_shipping"
    get "/settings/danger", to: "settings#danger", as: "danger_zone"

    get "/settings/subscription", to: "subscriptions#edit", as: "edit_subscription"
    post "/settings/subscription", to: "settings#create_portal", as: "create_user_portal"

    # Delete subscription
    delete "settings/subscription", to: "subscriptions#cancel", as: :cancel_subscription
    # Stripe connect
    get "/settings/payments/connect", to: "places#connect", as: :place_connect
    post "/settings/payments/connect", to: "places#create_stripe_account", as: :place_create_connect
    post "/settings/payments/connect/link", to: "places#create_account_link", as: :place_create_link

    resources :places, only: [:edit, :update, :new, :create, :index] do
      patch "/update_slug", to: "places#update_slug", as: "update_slug"
      patch "/update_delivery", to: "places#update_delivery", as: :update_delivery
    end


  end
  # get "/react-router(*all)", to: "home#react", as: "react"

end

app/views/utils/Headers/_dashboard.html.erb
<div class="relative w-full">
  <aside
    data-turbolinks-permanent
    class="bg-white flex items-start justify-start fixed left-0 w-1/5 h-screen flex-wrap z-40 mx-auto pb-6 pt-20 border-gray-300 border-r overflow-x-auto main-scroll">
    <div class="w-full flex flex-wrap items-center gap-4 mb-20 px-4">
      <div class="w-full truncate">
        <% if @place %>
          <% unless @place.new_record? %>
            <h4 class="font-bold flex items-center">
              <%= link_to place_path(@place.slug), target: "_blank" do %>
                        <span class="flex inline items-center truncate">
      <%= @place.name.truncate(25) %>
                          <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px"
                               class="h-4 inline ml-2"
                               viewBox="0 0 24 24"
                               style=" fill:#000000;">
                          <path d="M 5 3 C 3.9069372 3 3 3.9069372 3 5 L 3 19 C 3 20.093063 3.9069372 21 5 21 L 19 21 C 20.093063 21 21 20.093063 21 19 L 21 12 L 19 12 L 19 19 L 5 19 L 5 5 L 12 5 L 12 3 L 5 3 z M 14 3 L 14 5 L 17.585938 5 L 8.2929688 14.292969 L 9.7070312 15.707031 L 19 6.4140625 L 19 10 L 21 10 L 21 3 L 14 3 z"></path>
                        </svg>
                        </span>
              <% end %>

            </h4>
          <% end %>
        <% end %>
      </div>
      <div class="w-full main-scroll">
        <%= render "utils/Headers/dashboard/items" %>
      </div>
    </div>

  </aside>
  <% unless @place.kind == "premium" %>
    <div class="fixed bottom-0 left-0 z-50 bg-white flex shadow-top px-4 py-6 w-1/5">
      <%= link_to "Actualizar plan", dashboard_new_subscription_path("premium"), class: "text-center w-full #{main_color_button(color: "primary", size: "big", padding: "big")}" %>
    </div>
  <% end %>
</div>

app/views/utils/Headers/_simple.html.erb
<div class="w-full sticky top-0 border-b z-40">
  <div class="flex w-full gap-4 px-6 bg-white items-center h-20 justify-between">
    <div class="w-7/12 flex items-center gap-12">
      <div class="w-auto">
        <a href="/">
          <img
            draggable="false"
            src="<%= get_image_url(20, 100, "utils/w-logo-5.png") %>"
            class="h-10"
            alt="waydda logo"
            />
        </a>
      </div>
      <div class="w-10/12">
        <form
          class="w-full relative">
          <div class="absolute top-0 flex justify-center items-center left-0 bottom-0 h-full ml-4">
            <img
              class="h-5 opacity-75"
              alt="svgImg"
              src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHg9IjBweCIgeT0iMHB4Igp3aWR0aD0iOTYiIGhlaWdodD0iOTYiCnZpZXdCb3g9IjAgMCA0OCA0OCIKc3R5bGU9IiBmaWxsOiMwMDAwMDA7Ij48cGF0aCBkPSJNIDIwLjUgNiBDIDEyLjUxNTU1NiA2IDYgMTIuNTE1NTYyIDYgMjAuNSBDIDYgMjguNDg0NDM4IDEyLjUxNTU1NiAzNSAyMC41IDM1IEMgMjMuNzczMTU4IDM1IDI2Ljc4ODkxOSAzMy44OTMwMTggMjkuMjIwNzAzIDMyLjA1MDc4MSBMIDM4LjU4NTkzOCA0MS40MTQwNjIgQSAyLjAwMDIgMi4wMDAyIDAgMSAwIDQxLjQxNDA2MiAzOC41ODU5MzggTCAzMi4wNTA3ODEgMjkuMjIwNzAzIEMgMzMuODkzMDE3IDI2Ljc4ODkxOCAzNSAyMy43NzMxNTYgMzUgMjAuNSBDIDM1IDEyLjUxNTU2MiAyOC40ODQ0NDQgNiAyMC41IDYgeiBNIDIwLjUgMTAgQyAyNi4zMjI2ODUgMTAgMzEgMTQuNjc3MzE5IDMxIDIwLjUgQyAzMSAyMy4yOTU3MTEgMjkuOTE0MDY1IDI1LjgyMDYwMSAyOC4xNDg0MzggMjcuNjk3MjY2IEEgMi4wMDAyIDIuMDAwMiAwIDAgMCAyNy43MDExNzIgMjguMTQ0NTMxIEMgMjUuODI0MTAzIDI5LjkxMjQwMyAyMy4yOTc3MSAzMSAyMC41IDMxIEMgMTQuNjc3MzE1IDMxIDEwIDI2LjMyMjY4MSAxMCAyMC41IEMgMTAgMTQuNjc3MzE5IDE0LjY3NzMxNSAxMCAyMC41IDEwIHoiPjwvcGF0aD48L3N2Zz4="/>
          </div>
          <input type="search"
                 value="<%= params["search"].present? ? params["search"] : "" %>"
                 autoFocus="<%= params["search"].present? %>"
                 class="py-3 pl-12 pr-5 rounded-full bg-main-gray focus:outline-none w-full"
                 placeholder="Busca en tu ciudad"
            />
        </form>
      </div>
    </div>
    <div
      class="w-3/12">
      <div class="w-full">
        <%= render Shipment::Selecter.new(current_address: @current_address) %>
      </div>
      <%#= react_component("Shipment", props: {current_user: current_user, current_user_id: current_user ? current_user.id.to_s : nil, current_address: @current_address, locations: default_locations}, prerender: false) %>
    </div>
    <div class="w-2/12 px-0 flex items-center gap-3 justify-around">
      <%= render Header::Public::Cart.new(current_cart: @current_cart, cart_items: @cart_items, place: @place, as_guest: session[:continue_as_guest]) %>
      <div class="w-auto flex justify-center">
        <% if user_signed_in? %>
          <%= render "dashboard/utils/toggle", mt: "big" %>
        <% else %>
          <%= link_to "Inicia sesión", new_user_session_path, class: main_color_button(color: "primary") %>
        <% end %>
      </div>
      <%#= react_component("Simple", props: {current_user: current_user, current_user_id: current_user ? current_user.id.to_s : nil, current_address: @current_address, locations: default_locations}, prerender: false) %>
    </div>
  </div>
</div>