config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  # TODO: Agregar seguridad a esto
  # mount Split::Dashboard, at: 'split'
  # Business
  get "/business", to: "home#business", as: :home_business
  get "/pricing", to: "home#pricing", as: :price_business

  # search
  get "/search", to: "searchs#show", as: "search"
  # users
  devise_for :users, :controllers => {sessions: "users/sessions"}
  devise_scope :user do
    get 'acceder', to: 'users/sessions#new' #, as: :new_user_session
    post "/guest", to: "users/sessions#continue_as_guest", as: "continue_as_guest"
  end
  get "/my-profile", to: "users#my_profile", as: "my_profile"
  get "/my-profile/edit", to: "users#edit", as: "edit_my_profile"
  resources :users, only: [:show, :update] do
    collection do
      patch 'update_password'
    end
  end
  #Address
  resources :addresses

  #cart
  # delete "/delete_product/:product_id", to: "carts#delete_product", as: "delete_product_to_cart"
  # put "/update_item/:item_id", to: "carts#update_item", as: "update_item_to_cart"
  # post "/add_to_cart/:place_id/:product_id", to: "carts#add_product", as: "add_product_to_cart"

  # checkouts
  get 'checkout', to: "checkouts#show"
  resources :checkouts, only: [:show, :create]
  get "/cart", to: "carts#show", as: "my_public_cart"

  #Public places
  resources :places, only: [:show, :index], path: "place" do
    # get "/catalog", to: "places#catalog", as: :catalog
    put '/:cart_id/delivery-options', to: "delivery_options#update", as: "delivery_options"
    resources :products do
      post "/cart/add_item", to: "carts#add_product", as: "add_to_cart"
    end

    resources :items, path: "departments", only: [:index, :show]
    patch "/cart/:cart_item_id/update_item", to: "carts#update_item", as: "update_cart_item"
    get "/cart", to: "carts#show", as: "my_cart"
    get "/cart/edit", to: "carts#show", as: "edit_my_cart"
    post "/cart", to: "carts#create_charge", as: "create_charge"
    get "/:cart_id/success", to: "carts#success", as: "success_checkout"
    put "/cart/payment-method", to: "carts#payment_method", as: "update_payment_method"
  end

  # Dashboard
  get "/dashboard", to: "dashboard/places#my_place", as: "my_place" # Index dashboard
  # Webhooks
  post "/hooks", to: "dashboard/hooks#hooks"
  post "/hooks_connect", to: "dashboard/hooks#connect"
  # mount StripeEvent::Engine, at: '/hooks'
  namespace :dashboard do
    # Uploads
    post "/upload/:model/:slug/:attribute", to: "image#upload", as: "upload_image"
    get "/upgrade", to: "places#upgrade", as: :upgrade_plan
    get "/upgrade/:subscription_id", to: "subscriptions#new", as: :new_subscription
    post "/upgrade/:subscription_id", to: "subscriptions#create", as: :create_subscription
    # Payment Links
    resources :payment_links, only: [:index]
    resources :promotions, only: [:index]
    resources :loyalties, only: [:index]
    # Items
    resources :items, path: "departments" do
      delete "/:product_id", to: "items#remove_product", as: :remove_product
      get "/add-products", to: "items#add_products", as: :add_products
      post "/add-product/:product_id", to: "items#add_product", as: :add_product
    end
    resources :subscriptions, only: [:new]
    resources :customers, only: [:index, :show]
    # Products
    resources :products do
      post "/update_status", to: "products#update_status", as: :update_status
      get "/edit/inventory", to: "products#edit_inventory", as: :edit_inventory
      get "/edit/variants", to: "products#edit_variants", as: :edit_variants
      get "/edit/variants/new", to: "aggregate_categories#new", as: :new_variant
      get "/edit/variants/:id", to: "aggregate_categories#show", as: :edit_variant
      # patch "/edit/variants/:id", to: "aggregate_categories#update", as: :update_variant
      resources :aggregate_categories, :path => 'variants' do
        resources :aggregates
      end
    end
    # Places
    resources :orders do
      patch "/process", to: "orders#process_order", as: :process_item
      patch "/receive", to: "orders#receive_order", as: :receive_item
      patch "/send", to: "orders#send_order", as: :send_item
      patch "/cancel", to: "orders#cancel_order", as: :cancel_item
    end
    delete "/delete-place", to: "places#destroy", as: "destroy_my_place"
    get "/settings", to: "places#edit", as: "edit_my_place"
    get "/settings/general", to: "settings#general", as: "edit_general_my_place"
    get "/settings/shipping", to: "settings#shipping", as: "edit_shipping"
    get "/settings/danger", to: "settings#danger", as: "danger_zone"

    get "/settings/subscription", to: "subscriptions#edit", as: "edit_subscription"
    post "/settings/subscription", to: "settings#create_portal", as: "create_user_portal"

    # Delete subscription
    delete "settings/subscription", to: "subscriptions#cancel", as: :cancel_subscription
    # Stripe connect
    get "/settings/payments/connect", to: "places#connect", as: :place_connect
    post "/settings/payments/connect", to: "places#create_stripe_account", as: :place_create_connect
    post "/settings/payments/connect/link", to: "places#create_account_link", as: :place_create_link

    resources :places, only: [:edit, :update, :new, :create, :index] do
      patch "/update_slug", to: "places#update_slug", as: "update_slug"
      patch "/update_delivery", to: "places#update_delivery", as: :update_delivery
    end


  end
  # get "/react-router(*all)", to: "home#react", as: "react"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "business", only: [:business, :pricing]
  before_action :set_price

  def index
    set_meta_tags title: "Waydda México",
                  description: "Waydda México"
    @places = Place.where(status: "active").order_by(created_at: :desc).paginate(page: params[:page], per_page: 20)
  end

  def business
  end

  def pricing

  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/business.html.erb
<div
  class="w-full flex flex-wrap main-business">
  <div class="w-8/12 flex mx-auto mt-24">
    <div class="w-full flex flex-wrap">
      <div class="w-full flex justify-center text-center">
        <h2 class="text-main-red font-medium">Lo local en la palma de tu mano</h2>
      </div>
      <div class="w-full flex justify-center text-center mt-3">
        <h1 class="text-gray-900 font-bold text-5xl"><span class="notranslate">Waydda</span> conecta a
          <span class="text-teal-600">empresas</span> con sus
          consumidores <span class="text-teal-600">locales</span> y <span class="text-teal-600">nacionales</span></h1>
      </div>
      <div class="w-full mt-8 flex justify-center">
        <%= link_to "Empezar", new_dashboard_place_path({continue: user_signed_in? ? nil : new_dashboard_place_path}), class: "font-medium bg-main-red text-white rounded py-3 px-6 hover:bg-red-600 transition duration-150" %>
      </div>
      <div class="w-full flex justify-center">
        <img alt="Business page" src="<%= get_image_url(20, 20, "utils/cyborg-19.png") %>" class="lazy h-xxl" data-src="<%= get_image_url(1000, 800, "utils/cyborg-19.png") %>">
      </div>
    </div>
  </div>
</div>

<div class="bg-white min-h-screen flex w-full items-center">
  <div class="w-11/12 justify-between gap-12 mx-auto flex items-center">
    <div class="w-5/12 flex flex-wrap">
      <div class="w-full">
        <h4 class="text-main-red font-medium">
          Lipsa natus officiis quae quam
        </h4>
      </div>
      <div class="w-10/12">
        <h2 class="font-bold text-black text-4xl mt-3">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit.
        </h2>
      </div>
      <div class="w-full">
        <h3 class="font-normal tracking-wide text-sm leading-7 text-gray-600 mt-3">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem, similique velit! Beatae consequatur
          dicta doloribus eveniet expedita.
        </h3>
      </div>

      <div class="w-full mt-8">
        <%= link_to new_user_session_path, class: "rounded bg-main py-3 px-5 font-medium text-black hover:text-teal-600 flex items-center gap-4 w-6/12" do %>
          <!--        <span class="items-center gap-4" >-->
          <div class="w-9/12">
            Más información
          </div>
          <div class="w-3/12 flex justify-end">
            <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px"
                 width="16" height="16"
                 viewBox="0 0 50 50"
                 style=" fill:#000000;">
              <path d="M 37.058594 12.980469 C 36.246094 12.949219 35.492188 13.414063 35.160156 14.15625 C 34.824219 14.898438 34.96875 15.765625 35.53125 16.359375 L 41.675781 23 L 3 23 C 2.277344 22.988281 1.609375 23.367188 1.246094 23.992188 C 0.878906 24.613281 0.878906 25.386719 1.246094 26.007813 C 1.609375 26.632813 2.277344 27.011719 3 27 L 41.675781 27 L 35.53125 33.640625 C 35.03125 34.164063 34.855469 34.914063 35.066406 35.605469 C 35.277344 36.296875 35.84375 36.820313 36.546875 36.976563 C 37.253906 37.132813 37.988281 36.894531 38.46875 36.359375 L 48.972656 25 L 38.46875 13.640625 C 38.109375 13.242188 37.597656 13 37.058594 12.980469 Z"></path>
            </svg>
          </div>
          <!--        </span>-->
        <% end %>
      </div>
    </div>
    <div class="w-6/12">
      <img
        src="<%= get_image_url(20, 20, "utils/common-household-tools-on-wooden-background.jpg") %>" class="lazy shadow w-full h-full bg-gray-200" data-src="<%= get_image_url(1000, 700, "utils/common-household-tools-on-wooden-background.jpg") %>">
    </div>
  </div>
</div>

<div class="w-full bg-secondary-light mt-20 py-24 text-center">
  <div class="w-9/12 mx-auto flex flex-wrap text-center justify-center">
    <h2 class="text-black font-extrabold text-4xl">¡Únete y empieza a vender hoy!</h2>
    <div class="w-8/12 mt-8">
      <h3 class="font-normal">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis cum dolor doloribus
        exercitationem impedit inventore, ipsa ipsum iure laborum</h3>
    </div>
    <div class="w-full flex justify-center mt-8">
      <%= link_to "Registrarse", new_dashboard_place_path, class: "hover:bg-gray-900 transition duration-150 rounded flex w-3/12 text-white bg-black py-4 px-5 font-medium justify-center" %>
    </div>
    <div class="w-8/12 flex gap-4 justify-around mt-12">
      <div class="w-auto gap-2 flex items-center">
        <div class="w-auto">
          <svg
            class="w-4"
            xmlns="http://www.w3.org/2000/svg" x="0px" y="0px"
            viewBox="0 0 26 26"
            style=" fill:#000000;">
            <path d="M 22.566406 4.730469 L 20.773438 3.511719 C 20.277344 3.175781 19.597656 3.304688 19.265625 3.796875 L 10.476563 16.757813 L 6.4375 12.71875 C 6.015625 12.296875 5.328125 12.296875 4.90625 12.71875 L 3.371094 14.253906 C 2.949219 14.675781 2.949219 15.363281 3.371094 15.789063 L 9.582031 22 C 9.929688 22.347656 10.476563 22.613281 10.96875 22.613281 C 11.460938 22.613281 11.957031 22.304688 12.277344 21.839844 L 22.855469 6.234375 C 23.191406 5.742188 23.0625 5.066406 22.566406 4.730469 Z"></path>
          </svg>
        </div>
        <div class="w-auto">
          <span class="font-normal text-sm">X cosa</span>
        </div>
      </div>
      <div class="w-auto gap-2 flex items-center">
        <div class="w-auto">
          <svg
            class="w-4"
            xmlns="http://www.w3.org/2000/svg" x="0px" y="0px"
            viewBox="0 0 26 26"
            style=" fill:#000000;">
            <path d="M 22.566406 4.730469 L 20.773438 3.511719 C 20.277344 3.175781 19.597656 3.304688 19.265625 3.796875 L 10.476563 16.757813 L 6.4375 12.71875 C 6.015625 12.296875 5.328125 12.296875 4.90625 12.71875 L 3.371094 14.253906 C 2.949219 14.675781 2.949219 15.363281 3.371094 15.789063 L 9.582031 22 C 9.929688 22.347656 10.476563 22.613281 10.96875 22.613281 C 11.460938 22.613281 11.957031 22.304688 12.277344 21.839844 L 22.855469 6.234375 C 23.191406 5.742188 23.0625 5.066406 22.566406 4.730469 Z"></path>
          </svg>
        </div>
        <div class="w-auto">
          <span class="font-normal text-sm">X cosa</span>
        </div>
      </div>
      <div class="w-auto gap-2 flex items-center">
        <div class="w-auto">
          <svg
            class="w-4"
            xmlns="http://www.w3.org/2000/svg" x="0px" y="0px"
            viewBox="0 0 26 26"
            style=" fill:#000000;">
            <path d="M 22.566406 4.730469 L 20.773438 3.511719 C 20.277344 3.175781 19.597656 3.304688 19.265625 3.796875 L 10.476563 16.757813 L 6.4375 12.71875 C 6.015625 12.296875 5.328125 12.296875 4.90625 12.71875 L 3.371094 14.253906 C 2.949219 14.675781 2.949219 15.363281 3.371094 15.789063 L 9.582031 22 C 9.929688 22.347656 10.476563 22.613281 10.96875 22.613281 C 11.460938 22.613281 11.957031 22.304688 12.277344 21.839844 L 22.855469 6.234375 C 23.191406 5.742188 23.0625 5.066406 22.566406 4.730469 Z"></path>
          </svg>
        </div>
        <div class="w-auto">
          <span class="font-normal text-sm">X cosa</span>
        </div>
      </div>
    </div>
  </div>
  <div class="w-full mt-12 text-left flex justify-center items-start flex flex-wrap">
    <%= render Pricing::List::Index.new(place: @place, pricing: @premium_pricing, with_margin: true) %>
  </div>
</div>

app/views/home/index.html.erb
<div class="w-full h-xl bg-gray-300 mb-6">

</div>

<h1>Home#index</h1>
<h2>
  <%= link_to "Registrar mi empresa", home_business_path %>
</h2>
<%= link_to "Mi perfil", my_profile_path %>

app/views/home/pricing.html.erb
<h1>Hola</h1>

app/views/home/react.html.erb
<%= react_component("App", prerender: false) %>