config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  # TODO: Agregar seguridad a esto
  # mount Split::Dashboard, at: 'split'
  # Business
  get "/business", to: "home#business", as: :home_business
  get "/pricing", to: "home#pricing", as: :price_business

  # search
  get "/search", to: "searchs#show", as: "search"
  # users
  devise_for :users, :controllers => {sessions: "users/sessions"}
  devise_scope :user do
    get 'acceder', to: 'users/sessions#new' #, as: :new_user_session
    post "/guest", to: "users/sessions#continue_as_guest", as: "continue_as_guest"
  end
  get "/my-profile", to: "users#my_profile", as: "my_profile"
  get "/my-profile/edit", to: "users#edit", as: "edit_my_profile"
  resources :users, only: [:show, :update] do
    collection do
      patch 'update_password'
    end
  end
  #Address
  resources :addresses

  #cart
  # delete "/delete_product/:product_id", to: "carts#delete_product", as: "delete_product_to_cart"
  # put "/update_item/:item_id", to: "carts#update_item", as: "update_item_to_cart"
  # post "/add_to_cart/:place_id/:product_id", to: "carts#add_product", as: "add_product_to_cart"

  # checkouts
  get 'checkout', to: "checkouts#show"
  resources :checkouts, only: [:show, :create]
  get "/cart", to: "carts#show", as: "my_public_cart"

  #Public places
  resources :places, only: [:show, :index], path: "place" do
    # get "/catalog", to: "places#catalog", as: :catalog
    put '/:cart_id/delivery-options', to: "delivery_options#update", as: "delivery_options"
    resources :products do
      post "/cart/add_item", to: "carts#add_product", as: "add_to_cart"
    end

    resources :items, path: "departments", only: [:index, :show]
    patch "/cart/:cart_item_id/update_item", to: "carts#update_item", as: "update_cart_item"
    get "/cart", to: "carts#show", as: "my_cart"
    get "/cart/edit", to: "carts#show", as: "edit_my_cart"
    post "/cart", to: "carts#create_charge", as: "create_charge"
    get "/:cart_id/success", to: "carts#success", as: "success_checkout"
    put "/cart/payment-method", to: "carts#payment_method", as: "update_payment_method"
  end

  # Dashboard
  get "/dashboard", to: "dashboard/places#my_place", as: "my_place" # Index dashboard
  # Webhooks
  post "/hooks", to: "dashboard/hooks#hooks"
  post "/hooks_connect", to: "dashboard/hooks#connect"
  # mount StripeEvent::Engine, at: '/hooks'
  namespace :dashboard do
    # Uploads
    post "/upload/:model/:slug/:attribute", to: "image#upload", as: "upload_image"
    get "/upgrade", to: "places#upgrade", as: :upgrade_plan
    get "/upgrade/:subscription_id", to: "subscriptions#new", as: :new_subscription
    post "/upgrade/:subscription_id", to: "subscriptions#create", as: :create_subscription
    # Payment Links
    resources :payment_links, only: [:index]
    resources :promotions, only: [:index]
    resources :loyalties, only: [:index]
    # Items
    resources :items, path: "departments" do
      delete "/:product_id", to: "items#remove_product", as: :remove_product
      get "/add-products", to: "items#add_products", as: :add_products
      post "/add-product/:product_id", to: "items#add_product", as: :add_product
    end
    resources :subscriptions, only: [:new]
    resources :customers, only: [:index, :show]
    # Products
    resources :products do
      post "/update_status", to: "products#update_status", as: :update_status
      get "/edit/inventory", to: "products#edit_inventory", as: :edit_inventory
      get "/edit/variants", to: "products#edit_variants", as: :edit_variants
      get "/edit/variants/new", to: "aggregate_categories#new", as: :new_variant
      get "/edit/variants/:id", to: "aggregate_categories#show", as: :edit_variant
      # patch "/edit/variants/:id", to: "aggregate_categories#update", as: :update_variant
      resources :aggregate_categories, :path => 'variants' do
        resources :aggregates
      end
    end
    # Places
    resources :orders do
      patch "/process", to: "orders#process_order", as: :process_item
      patch "/receive", to: "orders#receive_order", as: :receive_item
      patch "/send", to: "orders#send_order", as: :send_item
      patch "/cancel", to: "orders#cancel_order", as: :cancel_item
    end
    delete "/delete-place", to: "places#destroy", as: "destroy_my_place"
    get "/settings", to: "places#edit", as: "edit_my_place"
    get "/settings/general", to: "settings#general", as: "edit_general_my_place"
    get "/settings/shipping", to: "settings#shipping", as: "edit_shipping"
    get "/settings/danger", to: "settings#danger", as: "danger_zone"

    get "/settings/subscription", to: "subscriptions#edit", as: "edit_subscription"
    post "/settings/subscription", to: "settings#create_portal", as: "create_user_portal"

    # Delete subscription
    delete "settings/subscription", to: "subscriptions#cancel", as: :cancel_subscription
    # Stripe connect
    get "/settings/payments/connect", to: "places#connect", as: :place_connect
    post "/settings/payments/connect", to: "places#create_stripe_account", as: :place_create_connect
    post "/settings/payments/connect/link", to: "places#create_account_link", as: :place_create_link

    resources :places, only: [:edit, :update, :new, :create, :index] do
      patch "/update_slug", to: "places#update_slug", as: "update_slug"
      patch "/update_delivery", to: "places#update_delivery", as: :update_delivery
    end


  end
  # get "/react-router(*all)", to: "home#react", as: "react"

end

app/models/place.rb
#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
# SENDGRID
class Place
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Geospatial
  include AASM
  include AlgoliaSearch
  include GlobalID::Identification
  require 'will_paginate/array'
# Rolify
  resourcify

# Algolia search
  algoliasearch do
    attributes :name, :address, :slug, :lat, :lng #, :city, :city_state
    geoloc :lat, :lng
  end

# Callbacks
  before_create :assign_slug
  after_create :add_owner_role

  field :name, type: String
  field :address, type: String
  field :external_number, type: String
  field :slug, type: String
  field :city, type: String
  field :city_state, type: String
  field :status, type: String, default: "active"
  field :lat, type: Float
  field :lng, type: Float
  field :location, type: Point
  field :photo, type: String, default: "places/default.png"
  field :cover, type: String, default: "waydda.png"
  field :total_items, type: Integer, default: 0
  field :total_products, type: Integer, default: 0
  field :kind, type: String, default: "free"
  field :trial_will_end, type: Boolean, default: false
  field :in_free_trial, type: Boolean, default: true
  field :trial_used, type: Boolean, default: false
  field :category, type: String
  field :other_category, type: String
  field :pickup_time, type: String, default: "0"
# DELIVERY
  field :delivery_option, type: Boolean, default: false
  field :delivery_cost, type: Float, default: 20
  field :delivery_distance, type: Float, default: 5
  field :delivery_extra_cost, type: Float, default: 0

# TODO: Añadir horarios de envío y recolección
# TODO: Añadir pedido minimo
# Relations
  belongs_to :user
  has_many :items
  has_many :products
  has_many :viewers
  has_many :views
  has_many :orders # Todas las ordenes que recibe
  has_one :subscription
  has_one :account

# Validations
  validates :name, presence: true, length: {in: 4..40}
  validates :address, presence: true, length: {in: 4..100}
  validates :status, presence: true, inclusion: {in: %w(pending active inactive)}
  validates :pickup_time, inclusion: {in: %w(0 1 2 3)}
  validates :category, inclusion: {in: %w(groceries food services other)}, allow_blank: true
  validates :other_category, length: {in: 0..40}, allow_blank: true
  validates :kind, presence: true, inclusion: {in: %w(free premium)}
  validates :slug, uniqueness: true
  validates :delivery_cost, numericality: {greater_than_or_equal_to: 0}
  validates :delivery_distance, numericality: {greater_than_or_equal_to: 0.3}
# validates :city, presence: true


  aasm column: :status do
    state :pending
    state :active, initial: true
    state :inactive

    event :activate do
      transitions from: [:pending, :inactive], to: :active
    end
    event :deactivate do
      transitions from: [:pending, :active], to: :inactive
    end
  end

  aasm column: :kind do
    state :free, initial: true
    state :premium

    event :to_premium do
      transitions from: [:free], to: :premium
    end
    event :to_free do
      transitions from: [:premium, :free], to: :free
    end
  end


# @param [Integer] quantity
# @param [Boolean] plus {true: +, false: - }
  def update_products_counter(quantity, plus)
    oper = plus ? self.total_products + quantity : self.total_products - quantity
    self.update(total_products: oper)
  end

# @note
# Función para calcular la distancia entre un place y un punto a
# @param [Array] point_a
# @return [Geokit::LatLng] KMS distance
  def get_distance(point_a = [])
    return 100000000 if point_a.length <= 0 # return 1000000 if point_a is empty
    a = Geokit::LatLng.new(self.lat, self.lng)
    b = Geokit::LatLng.new(point_a[0], point_a[1])
    a.distance_to(b)
  end

# @notice
# Función que nos retorna true/false que verifica que la distancia entre el punto a y delivery_distance
# sea menor o igual
# @param [Array] point_a
# @return [TrueClass, FalseClass]
  def available_distance?(point_a = [])
    self.get_distance(point_a) <= self.delivery_distance
  end


  def valid_sale?
    unless self.nil?
      logger.warn "Place is not active" unless self.status === "active"
      raise "Esta empresa no está disponible" unless self.status === "active"
      return self.status === "active"
    end
    raise "Esta empresa no está disponible"
    false
  end

# @note Retorna True, False si el place es un restaurante
# @return [TrueClass, FalseClass]
  def is_restaurant?
    if self.category
      return self.category === "food"
    else
      return false
    end
  end

  def self.get_pickup_times
    [["10 - 15 minutos", "0"], ["15 - 30 minutos", "1"], ["30 - 45 minutos", "2"], ["Más de una hora", "3"]]
  end

  def get_pickup_time
    Place.get_pickup_times.find { |a| a[1] === self.pickup_time }[0]
  end


  def valid_payment_methods
    if self.kind === "premium"
      if self.account.nil?
        return cash_array
      else
        if self.account.completed
          return complete_array
        else
          return cash_array
        end
      end
    else
      cash_array
    end
  end

  def complete_array
    [["Tarjeta de Débito/Crédito", "card"], %w[Efectivo cash]]
  end

  def cash_array
    [%w[Efectivo cash]]
  end

  def can_accept_payment_method?(payment_method:)
    if payment_method === "card"
      if self.kind === "premium"
        if self.account.nil?
          return false
        else
          if self.account.completed
            return true
          else
            return false
          end
        end
      else
        return false
      end
    else
      return true
    end
  end


  def can_delivery?
    self.kind === "premium" and self.delivery_option
  end


  private


  def self.current_categories
    [%w[Abarrotes groceries], %w[Alimentos food], %w[Servicios services], %w[Otros other]]
  end


  def self.cancel_subscription(subscription_id)
    get_subscription = Subscription.find_by(stripe_subscription_id: subscription_id)
    return nil if get_subscription.nil?
    current_place = get_subscription.place
    return nil if current_place.nil?
    puts "----------#{current_place.nil?} PLACE NIL #{subscription_id}"
    # current_subscription = Subscription.cancel_subscription(subscription_id)
    # puts "----------#{current_subscription} CANCEL SUBS"
    # return nil if current_subscription === false
    current_place.update(kind: "free", in_free_trial: false, trial_will_end: false)
    current_place.subscription.destroy
  end

  def self.update_attribute(attribute, id, new_value, current_user)
    place = Place.find_by(id: id)
    return {success: false, error: 'No se ha encontrado el recurso'} if place.nil? || place.pending?
    # PARENT -> User
    # Valid place owner
    return {success: false, error: 'No se ha encontrado el recurso'} unless current_user.id == place.user_id
    begin
      place.update("#{attribute}": new_value)
    rescue
      return {success: false, error: 'No se ha encontrado el recurso'}
    end
    return {success: true, error: nil}
  end


  def assign_slug
    loop do
      self.slug = "#{self.name.parameterize}-#{SecureRandom.hex(4)}"
      other_place = Place.find_by(slug: self.slug)
      break if other_place.nil?
    end
  end

  def add_owner_role
    self.user.add_role(:owner, self)
    self.user.update(is_admin: true)
  end

# @param [Object] user
# @return [Object] Account link
  def self.create_stripe_account_link(user)
    Account.create_stripe_account(self, user)
  end
end

app/controllers/dashboard/aggregate_categories_controller.rb
class Dashboard::AggregateCategoriesController < ApplicationController
  layout "dashboard"
  before_action :authenticate_user!
  before_action :set_my_place
  before_action :set_product
  before_action :set_aggregate_category, only: [:show, :update, :edit, :destroy]
  add_breadcrumb "Productos", :dashboard_products_path

  def new
    respond_to do |format|
      format.js
      format.html { redirect_to dashboard_product_edit_variants_path(@product) }
    end
    # set_meta_tags title: "Nueva variante de #{@product.name} | Panel de control",
    #               description: "Nueva variante de #{@product.name} | Panel de control"
    # add_breadcrumb "#{@product.name}", "#{dashboard_product_path(@product)}"
    # add_breadcrumb "Variantes", "#{dashboard_product_aggregate_categories_path(@product)}"
    # add_breadcrumb "Nueva variante"
    @aggregate_category = @product.aggregate_categories.new
    @aggregate_category.aggregates.new
  end

  def edit
    set_meta_tags title: "Editar variante: #{@aggregate_category.name} | Panel de control",
                  description: "Editar variante de #{@product.name} - Panel de control"
    add_breadcrumb " #{@product.name}", "#{dashboard_product_path(@product)}"
    add_breadcrumb "Variantes", "#{dashboard_product_aggregate_categories_path(@product)}"
    add_breadcrumb "#{@aggregate_category.name}", "#{dashboard_product_aggregate_category_path(@product, @aggregate_category)}"
    add_breadcrumb "Editar"
  end

  def show
    set_meta_tags title: "Variante: #{@aggregate_category.name} | Panel de control",
                  description: "Variante de #{@product.name} - Panel de control"
    add_breadcrumb "#{@product.name}", "#{dashboard_product_path(@product)}"
    add_breadcrumb "Variantes", "#{dashboard_product_aggregate_categories_path(@product)}"
    add_breadcrumb "#{@aggregate_category.name}"
    @aggregate_category.aggregates.build
    @aggregate_category_item = @aggregate_category
    @aggregate_category_item["custom_aggregates"] = @aggregate_category.aggregates.order(created_at: "desc")
  end

  def index
    set_meta_tags title: "Variantes de: #{@product.name} | Panel de control",
                  description: "Variantes de #{@product.name} - Panel de control"
    add_breadcrumb "#{@product.name}", "#{dashboard_product_path(@product)}"
    add_breadcrumb "Variantes"
    @aggregate_categories = @product.aggregate_categories
  end

  def create
    @aggregate_category = @product.aggregate_categories.new(aggregate_category_params)
    respond_to do |format|
      if @aggregate_category.save
        format.js
      else
        format.js
        # format.html{redirect_to dashboard_product_edit_variants_path(@product), notice: "Ha ocurrido un error al crear la variante"}
      end
    end
  end

  def update
    respond_to do |format|
      if @aggregate_category.update(aggregate_category_params)
        format.html { redirect_to dashboard_product_aggregate_category_path(@product, @aggregate_category), alert: "Se ha actualizado la variante" }
      else
        puts "-------#{@aggregate_category.errors.full_messages}"
        format.html { redirect_to dashboard_product_aggregate_category_path(@product, @aggregate_category), notice: "Ha ocurrido un error al actualizar la variante" }
      end
    end
  end

  def destroy
    @aggregate_category.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_product_aggregate_categories_path(@product), alert: "Se ha eliminado la variante" }
    end
  end

  private

  def set_product
    @product = @place.products.find_by(id: params["product_id"])
    not_found if @product.nil?
  end

  def set_aggregate_category
    (@aggregate_category = @product.aggregate_categories.find_by(id: params["id"])) or not_found
  end

  def aggregate_category_params
    params.require(:aggregate_category).permit(:name, :required, :multiple_selection, aggregates: [], aggregates_attributes: [:name, :unlimited, :price, :sku, :bar_code, :public_stock, :quantity, :_destroy,])
  end

end

app/controllers/dashboard/customers_controller.rb
class Dashboard::CustomersController < ApplicationController
  layout "dashboard"
  before_action :authenticate_user!
  before_action :set_my_place
  add_breadcrumb "Clientes", :dashboard_customers_path

  def index
  end

  def show
  end
end

app/controllers/dashboard/dashboard_controller.rb
class DashboardController < ApplicationController
  layout "dashboard"
  before_action :authenticate_user!, except: [:show]

  def index

  end

end

app/controllers/dashboard/loyalties_controller.rb
class Dashboard::LoyaltiesController < ApplicationController
  layout "dashboard"
  before_action :authenticate_user!
  before_action :set_my_place

  def index
  end
end

app/helpers/dashboard/aggregate_categories_helper.rb
module Dashboard::AggregateCategoriesHelper
end

app/views/dashboard/products/_form.html.erb
<div class="w-full flex flex-wrap py-8 mb-4 <%= border_color %>">
  <%= render Headers::Text.new(title: "Información básica", small: true, font: "small", padding_class: "px-4 pb-8") %>
  <div class="w-full px-4">
    <%= f.input :name, placeholder: "Nombre del producto", label: "Nombre del producto", input_html: {"x-on:input": "handleChange($event)"} %>
    <span name="product[name]_error" class="text-sm font-bold text-red-600"/>
  </div>
  <div class="w-full px-4">
    <%= f.input :description, as: :text, placeholder: "Descripción breve del producto", label: "Descripción", input_html: {"x-on:input": "handleChange($event)", "rows": "4"} %>
    <span name="product[description]_error" class="text-sm font-bold text-red-600"/>
  </div>
  <div class="w-full px-4">
    <%= f.input :weight, as: :float, placeholder: "Peso, kg", label: "Peso, KG", input_html: {"x-on:input": "handleChange($event)", "rows": "4"} %>
    <span name="product[weight]_error" class="text-sm font-bold text-red-600"/>
  </div>
</div>
<% if @complete_form %>
  <div class="w-full flex pb-4 mb-4 flex-wrap <%= border_color %>">
    <%= render Headers::Text.new(title: "Medidas de volumen", small: true, font: "small", padding_class: "px-4 py-4") %>
    <div class="w-full flex px-4">
      <div class="w-7/12 mr-2">
        <%= f.input :quantity,
                    placeholder: "Medida de volumen",
                    label: "Medida de volumen" %>
        <span name="product[quantity]_error" class="text-sm font-bold text-red-600"/>
      </div>
      <div class="w-5/12 ml-2">
        <%= f.input :quantity_measure,
                    collection: Product.current_measures,
                    prompt: "Selecciona una unidad",
                    label: "Unidad del volumen"
        %>
        <span name="product[quantity_measure]_error" class="text-sm font-bold text-red-600"/>
      </div>
    </div>
  </div>

<% end %>

app/views/dashboard/products/_last_sales.html.erb
<h2 class="font-normal text-xl"><%= message %></h2>
<% if @sales.length <= 0 %>
  <%= render "dashboard/utils/empty_records", message: "No tienes ningún envío pendiente 🥳" %>
<% else %>
  <% @sales.each do |v| %>
    <!--Code here-->
  <% end %>
<% end %>

app/views/dashboard/products/_sidebar.html.erb
<div class="w-full pb-4 mb-4 <%= border_color %>"
>
  <%= render Headers::Text.new(title: "Precio", small: true, font: "small", padding_class: "px-4 py-4", with_background: false, with_border: true) %>
  <div class="w-full px-4">
    <div class="w-full relative mt-6">
      <%= f.input :price,
                  as: :float,
                  placeholder: "Precio del producto",
                  label: false,
                  input_html: {
                      "x-on:input": "handleChange($event)",
                      class: "#{input_color_class} pl-16"
                  }
      %>
      <span name="product[price]_error" class="text-sm font-bold text-red-600"></span>
      <div class="absolute bottom-0 top-0 left-0 right-0 w-12 bg-main-gray-dark rounded-l flex items-center justify-center font-medium">$</div>
    </div>
  </div>
</div>
<div
  x-data="productSidebar(<%= @product.active? %>)"
  class="w-full pb-4 mb-4 <%= border_color %>">
  <%= render Headers::Text.new(title: "Disponibilidad", small: true, font: "small", padding_class: "px-4 py-4", with_background: false, with_border: true) %>
  <div class="w-full px-4">
    <div class="w-full relative mt-6">
      <div class="flex items-center mt-2">
        <%= f.input :status,
                    required: false,
                    as: :boolean, label: false, input_html: {class: "hidden"} %>
        <label class="switch">
          <input
            name="product[status]"
            type="checkbox"
            @change="isActive = !isActive"
            <%= @product.status === "active" ? "checked" : true %>
          >
          <span class="slider round"></span>
        </label>

        <div
          :class="{'hidden': isActive === false}"
          x-show="isActive" class="<%= @product.active? ? "" : "hidden" %>">
          <span class="text-sm font-normal text-green-700 ml-2">Activado</span>
        </div>
        <div
          :class="{'hidden': !isActive === false}"
          x-show="!isActive" class="<%= @product.active? ? "hidden" : "" %>">
          <span class="text-sm font-normal text-red-800 ml-2">Desactivado</span>
        </div>
      </div>
      <span name="product[status]_error" class="text-sm font-bold text-red-600"></span>
    </div>
  </div>
  <script type="text/javascript" charset="utf-8">
      function productSidebar(defaultActive = true) {
          return {
              isActive: defaultActive
          }
      }
  </script>
</div>
<div class="w-full flex flex-wrap pb-4 mb-4 <%= border_color %>">
  <%= render Headers::Text.new(title: "Categorías", small: true, font: "small", padding_class: "px-4 py-4", with_background: false, with_border: true) %>
  <div class="w-full px-4 flex">
    <%= f.input :item_ids,
                as: :check_boxes,
                collection: @place.items,
                label: false,
                input_html: {
                    class: "w-auto mr-4 mt-2 mb-4 cursor-pointer"
                },
                item_label_class: "w-full cursor-pointer select-none text-sm font-normal",
                item_wrapper_class: "w-full",
                wrapper_html: {
                    class: "flex flex-wrap",
                    id: "select_categories"
                }

    %>
    <span name="product[item_ids]_error" class="text-sm font-bold text-red-600"/>
  </div>
  <div class="w-full px-4 flex my-2">
    <%= link_to "+ Agregar departamento", new_dashboard_item_path, remote: true, class: "text-blue-700 hover:underline text-sm" %>
  </div>
</div>

app/views/dashboard/products/index.html.erb
<%= render Headers::Text.new(title: "Todos los productos", with_margin: false) do %>
  <%= main_button(to: new_dashboard_product_path, action: "add", text: "Agregar producto", color_button: "dark") %>
<% end %>

<% if @products.length > 0 %>
  <div class="flex w-full">
    <%= render Products::List.new(products: @products, in_dashboard: true, place: @place) %>
  </div>
  <div class="w-full flex justify-center mt-8">
    <%= will_paginate @products %>
  </div>
<% else %>
  <%= render EmptyRecords.new(title: params["page"] ? "Pagina #{params["page"]}, por aquí no hay nada 😕" : "Aún no hay productos por mostrar") %>
<% end %>

app/views/dashboard/products/show.html.erb
<%= content_for(:head_tags) do %>
  <meta name="content_slug" content="<%= @product.id.to_s %>"/>
  <meta name="content_model" content="product"/>
<% end %>
<div class="w-full flex gap-4 items-center flex-wrap justify-between px-4 py-4 <%= border_color %>">
  <div class="mt-8 flex flex-wrap">
    <div class="flex w-full">
      <img
        id="product_image"
        class="lazy h-24 rounded w-24 bg-gray-200"
        src="<%= get_image_url(10, 10, @product.photo, "cover") %>" data-src="<%= get_image_url(150, 150, @product.photo, "cover") %>" alt="<%= @product.name %> photo">
    </div>
  </div>
  <%= render Headers::Text.new(title: "#{@product.name}", subtitle: @product.description, small: true, with_border: false) do %>
    <%= main_button(text: "Editar producto", to: edit_dashboard_product_path(@product), action: "update", color_button: "dark") %>
  <% end %>
</div>

<div class="w-full mt-12 flex flex-wrap divide-y divide-gray-200 <%= border_color %>">
  <div class="w-full p-4 flex items-center">
    <h4 class="font-medium w-3/12">Estatus:</h4>
    <h5 class="text-gray-700 ml-2 text-sm font-normal inline"><%= @product.status === "active" ? "Activo" : "Desactivado" %></h5>
  </div>
  <div class="w-full p-4 flex items-center">
    <h4 class="font-medium w-3/12">Precio:</h4>
    <h5 class="text-gray-700 ml-2 text-sm font-normal inline"><%= number_to_currency(@product.price, format: "%u %n") %></h5>
  </div>
  <div class="w-full p-4 flex items-center">
    <h4 class="font-medium w-3/12">Descripción:</h4>
    <h5 class="ml-2 text-sm font-normal inline <%= @product.description.empty? ? "italic text-gray-500" : "text-gray-700" %>"><%= @product.description.empty? ? "Sin descripción" : @product.description %></h5>
  </div>
  <div class="w-full p-4 flex items-center">
    <h4 class="font-medium w-3/12">Productos en stock:</h4>
    <h5 class="text-gray-700 ml-2 text-sm font-normal inline"><%= pluralize(@product.public_stock, "unidad", plural: "unidades") %></h5>
  </div>
  <div class="w-full p-4 flex items-center">
    <h4 class="font-medium w-3/12">Vender sin stock:</h4>
    <h5 class="text-gray-700 ml-2 text-sm font-normal inline"><%= @product.unlimited ? "SI" : "NO" %></h5>
  </div>
  <div class="w-full p-4 flex items-center">
    <h4 class="font-medium w-3/12">Creado:</h4>
    <h5 class="ml-2 text-sm font-normal inline text-gray-700">Hace <%= time_ago_in_words(@product.created_at) %></h5>
  </div>
  <div class="w-full p-4 flex items-center">
    <h4 class="font-medium w-3/12">Visto por última vez:</h4>
    <h5 class="ml-2 text-sm font-normal inline <%= @product.last_viewed.nil? ? "text-gray-500 italic" : "text-gray-700" %>">
      <% if @product.last_viewed.nil? %>
        Nunca
      <% else %>
        Hace <%= time_ago_in_words(@product.last_viewed) %>
      <% end %>
    </h5>
  </div>
</div>

<div class="w-full flex mt-12 flex-wrap <%= border_color %>">
  <div class="w-full flex justify-between items-center px-3 py-4">
    <div class="w-3/12">
      <h3 class="text-lg mb-1 font-medium">
        Variantes
      </h3>
    </div>
    <div class="w-9/12 flex justify-end items-center">
      <%= link_to "Ver todas", dashboard_product_edit_variants_path(@product), class: "font-bold mr-6 hover:underline" %>
      <%= main_button(text: "Agregar variante", to: new_dashboard_product_aggregate_category_path(@product), action: "add") %>
    </div>
  </div>
  <div class="w-full">
    <%= render Dashboard::AggregateCategories::List::Index.new(product: @product) %>
  </div>
</div>
<div class="w-full p-4 my-12 <%= border_color %>">
  <%= render Headers::Text.new(title: "Área de peligro", with_border: false, subtitle: "Si eliminas el producto no podrás recuperar la información de este recurso, está acción es irreversible", small: true, with_margin: false) do %>
    <%= button_to "Eliminar producto", dashboard_product_path(@product), method: :delete, data: {confirm: "¿Estás seguro?", "disable-with": "Cargando..."}, class: main_color_button(color: "danger", size: "big", padding: "big"), remote: true %>
  <% end %>
</div>